services:
  influxdb:
    image: influxdb:2.7
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb2
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: admin123
      DOCKER_INFLUXDB_INIT_ORG: omni-org
      DOCKER_INFLUXDB_INIT_BUCKET: omni-bucket
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: SSU7o4kMPfkVgdnbFSyG-0POxLOL7T5bDvmsnt38Gn22abN46vxyQv0TQeUY-mZSGK3FFjLZT32d5OMxovBmmw==
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/health"]
      interval: 5s
      timeout: 5s
      retries: 30

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin123
      GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: /var/lib/grafana/dashboards/14801_rev2.json
    depends_on:
      influxdb:
        condition: service_healthy

  k6:
    image: grafana/k6:latest
    volumes:
      - ./scripts:/scripts
    depends_on:
      influxdb:
        condition: service_healthy
    entrypoint: ["/bin/sh", "-c"]
    command: >
       K6_INFLUXDB_ORG=omni-org
       K6_INFLUXDB_BUCKET=omni-bucket
       K6_INFLUXDB_TOKEN=SSU7o4kMPfkVgdnbFSyG-0POxLOL7T5bDvmsnt38Gn22abN46vxyQv0TQeUY-mZSGK3FFjLZT32d5OMxovBmmw==
       k6 run -o xk6-influxdb=http://influxdb:8086/ /scripts/script.js

volumes:
  influxdb-data:
  grafana-data: