#version: "3.8"

services:
  influxdb:
    image: influxdb:2.7
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb2
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: admin123
      DOCKER_INFLUXDB_INIT_ORG: omni-org
      DOCKER_INFLUXDB_INIT_BUCKET: omni-bucket
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: zML_Dm31864FA3uMs_4V8ZrGoqFeSuGVoz0iXk_1iADOlwG6u8OYoDqS7LuGBKbloXuqdNVKiQuBCABBHuSrcQ== # CHANGE THIS!
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/health"]
      interval: 5s
      timeout: 5s
      retries: 30

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/dashboards:/var/lib/grafana/dashboards # Mount dashboards
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin123
      GF_DASHBOARDS_PROVIDERS_ENABLE_UPDATE: "true" # Allow dashboard updates
      GF_DASHBOARDS_PROVIDERS_DEFAULT_HOME_DASHBOARD_PATH: /var/lib/grafana/dashboards/14801_rev2.json # set default dashboard
    depends_on:
      influxdb:
        condition: service_healthy

  k6:
      image: grafana/k6:latest
      volumes:
        - .scripts:/script.js
      environment:
        K6_INFLUXDB_ORGANIZATION: omni-org
        K6_INFLUXDB_TOKEN: zML_Dm31864FA3uMs_4V8ZrGoqFeSuGVoz0iXk_1iADOlwG6u8OYoDqS7LuGBKbloXuqdNVKiQuBCABBHuSrcQ==
      depends_on:
        influxdb:
          condition: service_healthy
      command: run -o xk6-influxdb=http://influxdb:8086/omni-bucket /scripts:/script.js

volumes:
  influxdb-data:
  grafana-data: